language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: benoitx-github
    token:
      secure: 13b70009cbae7646c3458517212a3ba73faff609
git:
  depth: false
env:
  global:
  - SONATYPE_USERNAME=benoitx
  - secure: MtZwtUKZtF83MDYsKbZeyJn0R9xvSFBA9jJpk1wQXJ/zZCQsNbBJGm8ez8l5x++tGwX5BvbEeH3rqWrul9gNLcNG5PXUnar5rAHUFAHnEr3OuPfKogkOGMXxK0xXWzeKIJx5nDAAPvqlMe7lGOogA60ZFfQM3CdHwbWlNo/xVVI=
  - secure: DSPCcO+Ny49IioFE8AHUyAEIVCP+j+5xJSyj3z9TvFfSgvLVrVPbhb62dkvheA0j2gaIOWVqivmqp3ZLzCDavyUZFzKtpp1Jo1SwcrG0kKG2dR/abQ8Vf2ct1n+5l0ebOQlAxVZnJpbAoKNYl3aT7wrOkrVtEAB4dUNaKUDJ7aU=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
    recipients:
    - opensource@appendium.com
    on_success: always
    on_failure: always
  slack:
    secure: hrRnpmD/K9ue2dGlob13noutgkFqP9xrfhRDG9tSje3sMSizWd7Yz7pIHqZesOrFKX8KqmBqsqgRyi83pX5Vp0DlAACsf15VReTdz9ogswKKPIRuaMb7CcgxqHM309CpdwlAsHIpSZ9NQyy/TCmYPw9eKIc9mGL+zJZUayf62iuJ0he5FDwuheSGUS5+aiK5T4UHu5cRzxB5bzMGzJDouoLcoKw5i2ceyFoDrJKHXzDdGoeRB/pNmAKhZBR3i1zkjxW412NHLhnpKIDElu6hjl4LFL2h5dh9irkTs9St7TMQCpmoa+mI7reMSUQlFIu+YyjRb3n9P7jcpqu4SJeb1v6p5yBqwLvq0sqQID8yqFHrBQnBpWl6K4vQx5+ummR2D0jvCT7aDid7OakXMYIN88vxBYq/LI/I56R1zsBhbwVCdhaCGvflc6j0SyEd/02kJbm196ZfXW/Kh4VjNtgWpQqQ9EBlGcIkFvx8fWrwZ1b193D/ZZD4+e/Kg66hH9KJ6Et/Jw4N6qTDRi4HsGk/rSp7VsGN5QlFxNWQRI8sOMOu5GKBCd9eqstTCh1rfY7xlgJ4tqQVwDgNdhF0UVly51Tywn09wYdznBnkJ9U0PisQIlCs5enySuV+e19ssoPFqrQAoVM06zxARwGBJiyh5eXldev5GwaavmVTiLTW9aY=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { python travis/addServer.py; mvn clean deploy
  --settings ~/.m2/mySettings.xml; };'
